name: Python Wechat Bot application

on:
  push:
    branches: master
  workflow_dispatch:
  #schedule:
    #- cron: '0 23,12 * * *'
    # cron表达式，Actions时区是UTC时间，所以上午9点要往前推8个小时

jobs:
  start:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install dependencies
      run: |
        pip install -r requirements.txt
    - name: Set selected color
      run: echo "::debug::Set the Octocat variable"
    - name: excute script
      run: |
        python run.py
